# Generated by Django 5.2.1 on 2025-05-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao_completa',
            field=models.TextField(blank=True, verbose_name='Descrição Completa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
